<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;
use NickWelsh\EloquentZero\Support\Mode;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\AliasedBlogPost;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\BlogPost;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\DangerousMethodModel;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\GeoThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\Group;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\Member;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\NumericAliasThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\ScopedComment;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\StaleBelongsToComment;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\StaleZeroColumnsThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\Subscriber;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\TodoItem;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\TodoList;

beforeEach(function () {
    Schema::dropIfExists('scoped_comments');
    Schema::dropIfExists('blog_posts');

    Schema::create('blog_posts', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('title');
    });
});

afterEach(function () {
    Schema::dropIfExists('scoped_comments');
    Schema::dropIfExists('blog_posts');
    Schema::dropIfExists('group_member');
    Schema::dropIfExists('groups');
    Schema::dropIfExists('geo_things');
    Schema::dropIfExists('dangerous_method_models');
    Schema::dropIfExists('included_notes');
    Schema::dropIfExists('ignored_notes');
    Schema::dropIfExists('members');
    Schema::dropIfExists('numeric_alias_things');
    Schema::dropIfExists('subscribers');
    Schema::dropIfExists('stale_belongs_to_comments');
    Schema::dropIfExists('stale_zero_columns_things');
    Schema::dropIfExists('todo_items');
    Schema::dropIfExists('todo_lists');
    DB::statement('DROP TYPE IF EXISTS todo_status');
});

it('generates a zero schema file for an explicit model', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-schema-test.ts';

    File::delete($outputPath);

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [BlogPost::class],
    ])->assertSuccessful();

    expect(File::exists($outputPath))->toBeTrue();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain('// @generated by eloquent-zero')
        ->toContain("const blogPost = table('blogPosts')")
        ->toContain("  .from('blog_posts')")
        ->toContain('id: string()')
        ->toContain('title: string()')
        ->toContain("  .primaryKey('id')")
        ->toContain('export const schema = createSchema({')
        ->toContain('export type Schema = Row<typeof schema>;')
        ->toContain("export type BlogPost = Schema['blogPosts'];")
        ->toContain('export const zql = createBuilder(schema)');
});

it('allows overriding the primary zero schema name with an attribute', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-aliased-schema-test.ts';

    File::delete($outputPath);

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [AliasedBlogPost::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const ThePost = table('ThePosts')")
        ->toContain("  .from('blog_posts')")
        ->toContain("export type ThePost = Schema['ThePosts'];")
        ->not->toContain("table('blogPosts')");
});

it('generates enum columns and one-to-many relationships from eloquent models', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-relationships-test.ts';

    File::delete($outputPath);

    DB::statement('DROP TYPE IF EXISTS todo_status');
    DB::statement("CREATE TYPE todo_status AS ENUM ('active', 'backlog', 'archived')");

    Schema::create('todo_lists', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('name');
        $table->timestamp('created_at');
        $table->timestamp('updated_at');
    });

    DB::statement('ALTER TABLE todo_lists ADD COLUMN status todo_status NOT NULL');

    Schema::create('todo_items', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('todo_list_id');
        $table->string('title');
        $table->timestamp('completed_at')->nullable();
        $table->timestamp('created_at');
        $table->timestamp('updated_at');
        $table->foreign('todo_list_id')->references('id')->on('todo_lists');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [TodoList::class, TodoItem::class],
    ])->assertSuccessful();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain("const todoList = table('todoLists')")
        ->toContain("status: enumeration<'active' | 'backlog' | 'archived'>()")
        ->toContain("completedAt: number().from('completed_at').optional()")
        ->toContain('const todoListRelationships = relationships(')
        ->toContain('todoItems: many({')
        ->toContain('destSchema: todoItem')
        ->toContain("destField: ['todoListId']")
        ->toContain('const todoItemRelationships = relationships(')
        ->toContain('todoList: one({')
        ->toContain("sourceField: ['todoListId']")
        ->toContain('relationships: [todoListRelationships, todoItemRelationships]');
});

it('discovers models from configured directories and skips ignored models in opt-out mode', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-discovery-test.ts';

    File::delete($outputPath);

    Schema::create('included_notes', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('body');
    });

    Schema::create('ignored_notes', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('body');
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.mode', Mode::OptOut);
    config()->set('eloquent-zero.model_search_directories', [
        __DIR__.'/../Fixtures/DiscoveryModels',
    ]);
    config()->set('eloquent-zero.models', []);

    $this->artisan('generate:zero-schema')->assertSuccessful();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain("const includedNote = table('includedNotes')")
        ->not->toContain("const ignoredNote = table('ignoredNotes')");
});

it('falls back to a single usable unique index when no primary key exists', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-unique-test.ts';

    File::delete($outputPath);

    Schema::create('subscribers', function (Blueprint $table): void {
        $table->string('email')->unique();
        $table->string('name');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [Subscriber::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const subscriber = table('subscribers')")
        ->toContain("  .primaryKey('email')");
});

it('generates many-to-many relationships from belongs-to-many relations', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-many-to-many-test.ts';

    File::delete($outputPath);

    Schema::create('members', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    Schema::create('groups', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    Schema::create('group_member', function (Blueprint $table): void {
        $table->string('member_id');
        $table->string('group_id');
        $table->primary(['member_id', 'group_id']);
        $table->foreign('member_id')->references('id')->on('members');
        $table->foreign('group_id')->references('id')->on('groups');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [Member::class, Group::class],
    ])->assertSuccessful();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain("const groupMember = table('groupMember')")
        ->toContain('groups: many(')
        ->toContain('destSchema: groupMember')
        ->toContain("destField: ['memberId']")
        ->toContain('destSchema: group')
        ->toContain("destField: ['id']")
        ->toContain('members: many(');
});

it('forces required foreign keys back into zero columns allowlists', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-zero-columns-test.ts';

    File::delete($outputPath);
    Schema::dropIfExists('scoped_comments');
    Schema::dropIfExists('blog_posts');

    Schema::create('blog_posts', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('title');
    });

    Schema::create('scoped_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
        $table->string('title');
        $table->string('secret_text');
        $table->foreign('blog_post_id')->references('id')->on('blog_posts');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [BlogPost::class, ScopedComment::class],
    ])
        ->expectsOutputToContain('Forcing column [scoped_comments.blog_post_id] into schema because it is required.')
        ->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("blogPostId: string().from('blog_post_id')")
        ->not->toContain('secretText');
});

it('warns and skips unsupported non-key columns', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-unsupported-test.ts';

    File::delete($outputPath);

    Schema::create('geo_things', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    DB::statement('ALTER TABLE geo_things ADD COLUMN location point');

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [GeoThing::class],
    ])
        ->expectsOutputToContain('Warning: Unsupported column type [point] on [geo_things.location]; skipping column.')
        ->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const geoThing = table('geoThings')")
        ->not->toContain('location:');
});

it('does not invoke arbitrary public model methods while discovering relations', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-dangerous-method-test.ts';

    File::delete($outputPath);

    Schema::create('dangerous_method_models', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [DangerousMethodModel::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const dangerousMethodModel = table('dangerousMethodModels')");
});

it('maps postgres numeric aliases like int8 to number columns', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-numeric-alias-test.ts';

    File::delete($outputPath);

    Schema::create('numeric_alias_things', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    DB::statement('ALTER TABLE numeric_alias_things ADD COLUMN counter bigint NOT NULL');

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [NumericAliasThing::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain('counter: number()');
});

it('throws when a declared relation no longer matches database columns', function () {
    Schema::create('stale_belongs_to_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
    });

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [BlogPost::class, StaleBelongsToComment::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-stale-relation-test.ts',
    ]))->toThrow(RuntimeException::class, 'Relation [StaleBelongsToComment::blogPost] references missing column [stale_belongs_to_comments.missing_blog_post_id].');
});

it('throws when zero columns references a missing database column', function () {
    Schema::create('stale_zero_columns_things', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [StaleZeroColumnsThing::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-stale-columns-test.ts',
    ]))->toThrow(RuntimeException::class, 'ZeroColumns on [stale_zero_columns_things] references missing column [missing_column].');
});

it('throws early when there are pending migrations', function () {
    $migrationPath = sys_get_temp_dir().'/eloquent-zero-pending-migrations';

    File::ensureDirectoryExists($migrationPath);
    File::put(
        $migrationPath.'/2099_01_01_000000_create_pending_table.php',
        <<<'PHP'
        <?php

        use Illuminate\Database\Migrations\Migration;
        use Illuminate\Database\Schema\Blueprint;
        use Illuminate\Support\Facades\Schema;

        return new class extends Migration
        {
            public function up(): void
            {
                Schema::create('pending_table', function (Blueprint $table): void {
                    $table->id();
                });
            }
        };
        PHP
    );

    app('migrator')->path($migrationPath);

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [BlogPost::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-pending-migration-test.ts',
    ]))->toThrow(RuntimeException::class, 'Database schema may be out of date. Run `php artisan migrate` before generating a Zero schema.');
});
