<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;
use NickWelsh\EloquentZero\Support\Mode;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\AliasedBlogPost;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\BlogPost;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\DangerousMethodModel;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\DuplicateJsonTypedThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\ExplicitJsonTypeBeatsCastThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\GeoThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\Group;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\JsonCastThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\JsonTypedThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\Member;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\NonJsonTypedThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\NumericAliasThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\PolymorphicRole;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\PolymorphicUser;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\RelationExcludedComment;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\ScopedComment;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\StaleBelongsToComment;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\StaleZeroColumnsThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\Subscriber;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\TodoItem;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\TodoList;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\WayfinderJsonTypedThing;
use NickWelsh\EloquentZero\Tests\Fixtures\Models\ZeroExcludedComment;

beforeEach(function () {
    config()->set('app.id', 'eloquent-zero-test');
    config()->set('eloquent-zero.publication_name', null);
    config()->set('eloquent-zero.use_wayfinder', false);

    DB::statement('DROP PUBLICATION IF EXISTS "_eloquent-zero-test_public_0"');
    DB::statement('DROP PUBLICATION IF EXISTS "custom_zero_publication"');

    Schema::dropIfExists('scoped_comments');
    Schema::dropIfExists('blog_posts');

    Schema::create('blog_posts', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('title');
    });
});

afterEach(function () {
    Schema::dropIfExists('scoped_comments');
    Schema::dropIfExists('blog_posts');
    Schema::dropIfExists('group_member');
    Schema::dropIfExists('groups');
    Schema::dropIfExists('geo_things');
    Schema::dropIfExists('glob_notes');
    Schema::dropIfExists('dangerous_method_models');
    Schema::dropIfExists('included_notes');
    Schema::dropIfExists('ignored_notes');
    Schema::dropIfExists('json_typed_things');
    Schema::dropIfExists('members');
    Schema::dropIfExists('manual_audit_entries');
    Schema::dropIfExists('model_has_roles');
    Schema::dropIfExists('numeric_alias_things');
    Schema::dropIfExists('polymorphic_users');
    Schema::dropIfExists('roles');
    Schema::dropIfExists('subscribers');
    Schema::dropIfExists('stale_belongs_to_comments');
    Schema::dropIfExists('stale_zero_columns_things');
    Schema::dropIfExists('todo_items');
    Schema::dropIfExists('todo_lists');
    DB::statement('DROP PUBLICATION IF EXISTS "_eloquent-zero-test_public_0"');
    DB::statement('DROP PUBLICATION IF EXISTS "custom_zero_publication"');
    DB::statement('DROP TYPE IF EXISTS todo_status');
});

it('generates a zero schema file for an explicit model', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-schema-test.ts';

    File::delete($outputPath);

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [BlogPost::class],
    ])->assertSuccessful();

    expect(File::exists($outputPath))->toBeTrue();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain('// @generated by eloquent-zero')
        ->toContain("const blogPost = table('blogPosts')")
        ->toContain("  .from('blog_posts')")
        ->toContain('id: string()')
        ->toContain('title: string()')
        ->toContain("  .primaryKey('id')")
        ->toContain('export const schema = createSchema({')
        ->toContain('export type Schema = Row<typeof schema>;')
        ->toContain("export type BlogPost = Schema['blogPosts'];")
        ->toContain('export const zql = createBuilder(schema)');
});

it('allows overriding the primary zero schema name with an attribute', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-aliased-schema-test.ts';

    File::delete($outputPath);

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [AliasedBlogPost::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const ThePost = table('ThePosts')")
        ->toContain("  .from('blog_posts')")
        ->toContain("export type ThePost = Schema['ThePosts'];")
        ->not->toContain("table('blogPosts')");
});

it('generates enum columns and one-to-many relationships from eloquent models', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-relationships-test.ts';

    File::delete($outputPath);

    DB::statement('DROP TYPE IF EXISTS todo_status');
    DB::statement("CREATE TYPE todo_status AS ENUM ('active', 'backlog', 'archived')");

    Schema::create('todo_lists', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('name');
        $table->timestamp('created_at');
        $table->timestamp('updated_at');
    });

    DB::statement('ALTER TABLE todo_lists ADD COLUMN status todo_status NOT NULL');

    Schema::create('todo_items', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('todo_list_id');
        $table->string('title');
        $table->timestamp('completed_at')->nullable();
        $table->timestamp('created_at');
        $table->timestamp('updated_at');
        $table->foreign('todo_list_id')->references('id')->on('todo_lists');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [TodoList::class, TodoItem::class],
    ])->assertSuccessful();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain("const todoList = table('todoLists')")
        ->toContain("status: enumeration<'active' | 'backlog' | 'archived'>()")
        ->toContain("completedAt: number().from('completed_at').optional()")
        ->toContain('const todoListRelationships = relationships(')
        ->toContain('todoItems: many({')
        ->toContain('destSchema: todoItem')
        ->toContain("destField: ['todoListId']")
        ->toContain('const todoItemRelationships = relationships(')
        ->toContain('todoList: one({')
        ->toContain("sourceField: ['todoListId']")
        ->toContain('relationships: [todoListRelationships, todoItemRelationships]');
});

it('discovers models from configured directories and skips ignored models in opt-out mode', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-discovery-test.ts';

    File::delete($outputPath);

    Schema::create('included_notes', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('body');
    });

    Schema::create('ignored_notes', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('body');
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.mode', Mode::OptOut);
    config()->set('eloquent-zero.model_search_directories', [
        __DIR__.'/../Fixtures/DiscoveryModels',
    ]);
    config()->set('eloquent-zero.models', []);

    $this->artisan('generate:zero-schema')->assertSuccessful();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain("const includedNote = table('includedNotes')")
        ->not->toContain("const ignoredNote = table('ignoredNotes')");
});

it('discovers models from configured glob directories', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-glob-discovery-test.ts';

    File::delete($outputPath);

    Schema::create('glob_notes', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('body');
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.mode', Mode::OptOut);
    config()->set('eloquent-zero.model_search_directories', [
        __DIR__.'/../Fixtures/DiscoveryModules/*/Models',
    ]);
    config()->set('eloquent-zero.models', []);

    $this->artisan('generate:zero-schema')->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const globNote = table('globNotes')");
});

it('falls back to a single usable unique index when no primary key exists', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-unique-test.ts';

    File::delete($outputPath);

    Schema::create('subscribers', function (Blueprint $table): void {
        $table->string('email')->unique();
        $table->string('name');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [Subscriber::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const subscriber = table('subscribers')")
        ->toContain("  .primaryKey('email')");
});

it('generates many-to-many relationships from belongs-to-many relations', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-many-to-many-test.ts';

    File::delete($outputPath);

    Schema::create('members', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    Schema::create('groups', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    Schema::create('group_member', function (Blueprint $table): void {
        $table->string('member_id');
        $table->string('group_id');
        $table->primary(['member_id', 'group_id']);
        $table->foreign('member_id')->references('id')->on('members');
        $table->foreign('group_id')->references('id')->on('groups');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [Member::class, Group::class],
    ])->assertSuccessful();

    $contents = File::get($outputPath);

    expect($contents)
        ->toContain("const groupMember = table('groupMember')")
        ->toContain('groups: many(')
        ->toContain('destSchema: groupMember')
        ->toContain("destField: ['memberId']")
        ->toContain('destSchema: group')
        ->toContain("destField: ['id']")
        ->toContain('members: many(');
});

it('warns and skips polymorphic many-to-many relationships', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-polymorphic-many-to-many-test.ts';

    File::delete($outputPath);

    Schema::create('polymorphic_users', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    Schema::create('roles', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    Schema::create('model_has_roles', function (Blueprint $table): void {
        $table->string('role_id');
        $table->string('model_type');
        $table->string('model_id');
        $table->primary(['role_id', 'model_id', 'model_type']);
        $table->foreign('role_id')->references('id')->on('roles');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [PolymorphicUser::class, PolymorphicRole::class],
    ])
        ->expectsOutputToContain('Warning: Unsupported polymorphic relation [PolymorphicUser::roles]; Zero relationships cannot express morph type constraints.')
        ->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const polymorphicUser = table('polymorphicUsers')")
        ->toContain("const role = table('roles')")
        ->not->toContain("const modelHasRole = table('modelHasRoles')")
        ->not->toContain('roles: many(');
});

it('generates configured tables without models', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-configured-tables-test.ts';

    File::delete($outputPath);

    Schema::create('manual_audit_entries', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('subject_id');
        $table->string('subject_type');
        $table->json('metadata')->nullable();
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.tables', [
        'manual_audit_entries' => ['id', 'subject_id', 'subject_type'],
    ]);

    $this->artisan('generate:zero-schema')->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const manualAuditEntry = table('manualAuditEntries')")
        ->toContain("  .from('manual_audit_entries')")
        ->toContain('subjectId: string()')
        ->toContain('subjectType: string()')
        ->not->toContain('metadata');
});

it('forces required foreign keys back into zero columns allowlists', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-zero-columns-test.ts';

    File::delete($outputPath);
    Schema::dropIfExists('scoped_comments');
    Schema::dropIfExists('blog_posts');

    Schema::create('blog_posts', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('title');
    });

    Schema::create('scoped_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
        $table->string('title');
        $table->string('secret_text');
        $table->foreign('blog_post_id')->references('id')->on('blog_posts');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [BlogPost::class, ScopedComment::class],
    ])
        ->expectsOutputToContain('Forcing column [scoped_comments.blog_post_id] into schema because it is required.')
        ->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("blogPostId: string().from('blog_post_id')")
        ->not->toContain('secretText');
});

it('warns and skips unsupported non-key columns', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-unsupported-test.ts';

    File::delete($outputPath);

    Schema::create('geo_things', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    DB::statement('ALTER TABLE geo_things ADD COLUMN location point');

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [GeoThing::class],
    ])
        ->expectsOutputToContain('Warning: Unsupported column type [point] on [geo_things.location]; skipping column.')
        ->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const geoThing = table('geoThings')")
        ->not->toContain('location:');
});

it('plans publication sql from hidden columns by default', function () {
    Schema::create('scoped_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
        $table->string('title');
        $table->string('secret_text');
        $table->foreign('blog_post_id')->references('id')->on('blog_posts');
    });

    Artisan::call('zero:sync-publication', [
        '--model' => [BlogPost::class, ScopedComment::class],
        '--dry-run' => true,
    ]);

    expect(Artisan::output())
        ->toContain('DROP PUBLICATION IF EXISTS "_eloquent-zero-test_public_0";')
        ->toContain('CREATE PUBLICATION "_eloquent-zero-test_public_0" FOR TABLE')
        ->toContain('"blog_posts"')
        ->toContain('"scoped_comments"')
        ->toContain('"blog_post_id"')
        ->toContain('"title"')
        ->not->toContain('"secret_text"');
});

it('uses ZeroExclude instead of hidden columns for publication sync', function () {
    Schema::create('scoped_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
        $table->string('title');
        $table->string('secret_text');
        $table->foreign('blog_post_id')->references('id')->on('blog_posts');
    });

    $this->artisan('zero:sync-publication', [
        '--model' => [BlogPost::class, ZeroExcludedComment::class],
        '--dry-run' => true,
    ])
        ->expectsOutputToContain('CREATE PUBLICATION "_eloquent-zero-test_public_0" FOR TABLE "blog_posts", "scoped_comments" ("id", "blog_post_id", "secret_text");')
        ->assertSuccessful();
});

it('forces required relation columns back into publication', function () {
    Schema::create('scoped_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
        $table->string('title');
        $table->string('secret_text');
        $table->foreign('blog_post_id')->references('id')->on('blog_posts');
    });

    $this->artisan('zero:sync-publication', [
        '--model' => [BlogPost::class, RelationExcludedComment::class],
        '--name' => 'custom_zero_publication',
        '--dry-run' => true,
    ])
        ->expectsOutputToContain('Warning: Forcing column [scoped_comments.blog_post_id] into publication because it is required.')
        ->expectsOutputToContain('CREATE PUBLICATION "custom_zero_publication" FOR TABLE "blog_posts", "scoped_comments" ("id", "blog_post_id", "secret_text");')
        ->assertSuccessful();
});

it('creates postgres publication', function () {
    Schema::create('scoped_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
        $table->string('title');
        $table->string('secret_text');
        $table->foreign('blog_post_id')->references('id')->on('blog_posts');
    });

    $this->artisan('zero:sync-publication', [
        '--model' => [BlogPost::class, ScopedComment::class],
        '--name' => 'custom_zero_publication',
    ])
        ->expectsOutputToContain('CREATE PUBLICATION "custom_zero_publication" FOR TABLE "blog_posts", "scoped_comments" ("id", "blog_post_id", "title");')
        ->assertSuccessful();

    $publication = DB::selectOne(
        'select pubname from pg_publication where pubname = ?',
        ['custom_zero_publication'],
    );

    expect($publication?->pubname)->toBe('custom_zero_publication');
});

it('syncs configured tables without models into publication', function () {
    Schema::create('manual_audit_entries', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('subject_id');
        $table->string('subject_type');
        $table->json('metadata')->nullable();
    });

    config()->set('eloquent-zero.tables', [
        'manual_audit_entries' => ['id', 'subject_id'],
    ]);

    $this->artisan('zero:sync-publication', [
        '--name' => 'custom_zero_publication',
        '--dry-run' => true,
    ])
        ->expectsOutputToContain('CREATE PUBLICATION "custom_zero_publication" FOR TABLE "manual_audit_entries" ("id", "subject_id");')
        ->assertSuccessful();
});

it('does not invoke arbitrary public model methods while discovering relations', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-dangerous-method-test.ts';

    File::delete($outputPath);

    Schema::create('dangerous_method_models', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [DangerousMethodModel::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("const dangerousMethodModel = table('dangerousMethodModels')");
});

it('maps postgres numeric aliases like int8 to number columns', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-numeric-alias-test.ts';

    File::delete($outputPath);

    Schema::create('numeric_alias_things', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    DB::statement('ALTER TABLE numeric_alias_things ADD COLUMN counter bigint NOT NULL');

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [NumericAliasThing::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain('counter: number()');
});

it('generates imported custom json column types', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-json-type-test.ts';

    File::delete($outputPath);

    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    config()->set('eloquent-zero.output_path', $outputPath);

    $this->artisan('generate:zero-schema', [
        '--model' => [JsonTypedThing::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("import type { RelationMetadata } from '@/types/crm';")
        ->toContain('metadata: json<RelationMetadata>().optional()');
});

it('uses imported json types even when wayfinder is enabled', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-json-import-wayfinder-test.ts';

    File::delete($outputPath);

    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.use_wayfinder', true);

    $this->artisan('generate:zero-schema', [
        '--model' => [JsonTypedThing::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("import type { RelationMetadata } from '@/types/crm';")
        ->toContain('metadata: json<RelationMetadata>().optional()')
        ->not->toContain('json<NickWelsh');
});

it('generates wayfinder custom json column types', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-json-wayfinder-test.ts';

    File::delete($outputPath);

    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.use_wayfinder', true);

    $this->artisan('generate:zero-schema', [
        '--model' => [WayfinderJsonTypedThing::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain('metadata: json<NickWelsh.EloquentZero.Tests.Fixtures.Types.RelationMetadata>().optional()')
        ->not->toContain('import type { RelationMetadata }');
});

it('throws when custom json class type has no import and wayfinder is disabled', function () {
    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [WayfinderJsonTypedThing::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-json-no-import-test.ts',
    ]))->toThrow(RuntimeException::class, 'ZeroJson on [json_typed_things.metadata] requires an import when use_wayfinder is false.');
});

it('throws when custom json type references non-json column', function () {
    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [NonJsonTypedThing::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-json-non-json-test.ts',
    ]))->toThrow(RuntimeException::class, 'ZeroJson on [json_typed_things.name] references non-JSON column [varchar].');
});

it('throws when custom json type is duplicated for a column', function () {
    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [DuplicateJsonTypedThing::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-json-duplicate-test.ts',
    ]))->toThrow(RuntimeException::class, 'Duplicate ZeroJson definition for [json_typed_things.metadata].');
});

it('infers json column types from class casts when wayfinder is enabled', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-json-cast-wayfinder-test.ts';

    File::delete($outputPath);

    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.use_wayfinder', true);

    $this->artisan('generate:zero-schema', [
        '--model' => [JsonCastThing::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain('metadata: json<NickWelsh.EloquentZero.Tests.Fixtures.Types.SettingsData>().optional()');
});

it('prefers explicit custom json types over cast inference', function () {
    $outputPath = sys_get_temp_dir().'/eloquent-zero-json-explicit-beats-cast-test.ts';

    File::delete($outputPath);

    Schema::create('json_typed_things', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->json('metadata')->nullable();
        $table->string('name');
    });

    config()->set('eloquent-zero.output_path', $outputPath);
    config()->set('eloquent-zero.use_wayfinder', true);

    $this->artisan('generate:zero-schema', [
        '--model' => [ExplicitJsonTypeBeatsCastThing::class],
    ])->assertSuccessful();

    expect(File::get($outputPath))
        ->toContain("import type { RelationMetadata } from '@/types/crm';")
        ->toContain('metadata: json<RelationMetadata>().optional()')
        ->not->toContain('SettingsData');
});

it('throws when a declared relation no longer matches database columns', function () {
    Schema::create('stale_belongs_to_comments', function (Blueprint $table): void {
        $table->string('id')->primary();
        $table->string('blog_post_id');
    });

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [BlogPost::class, StaleBelongsToComment::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-stale-relation-test.ts',
    ]))->toThrow(RuntimeException::class, 'Relation [StaleBelongsToComment::blogPost] references missing column [stale_belongs_to_comments.missing_blog_post_id].');
});

it('throws when zero columns references a missing database column', function () {
    Schema::create('stale_zero_columns_things', function (Blueprint $table): void {
        $table->string('id')->primary();
    });

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [StaleZeroColumnsThing::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-stale-columns-test.ts',
    ]))->toThrow(RuntimeException::class, 'ZeroColumns on [stale_zero_columns_things] references missing column [missing_column].');
});

it('throws early when there are pending migrations', function () {
    $migrationPath = sys_get_temp_dir().'/eloquent-zero-pending-migrations';

    File::ensureDirectoryExists($migrationPath);
    File::put(
        $migrationPath.'/2099_01_01_000000_create_pending_table.php',
        <<<'PHP'
        <?php

        use Illuminate\Database\Migrations\Migration;
        use Illuminate\Database\Schema\Blueprint;
        use Illuminate\Support\Facades\Schema;

        return new class extends Migration
        {
            public function up(): void
            {
                Schema::create('pending_table', function (Blueprint $table): void {
                    $table->id();
                });
            }
        };
        PHP
    );

    app('migrator')->path($migrationPath);

    expect(fn () => Artisan::call('generate:zero-schema', [
        '--model' => [BlogPost::class],
        '--path' => sys_get_temp_dir().'/eloquent-zero-pending-migration-test.ts',
    ]))->toThrow(RuntimeException::class, 'Database schema may be out of date. Run `php artisan migrate` before generating a Zero schema.');
});
